#########################################################################################################
-- This document was created with the purpose of provide the code snippers necessary to follow the text 
-- processing workshop. A PowerPoint presentation with other learning material will be provide after the
-- session. The code must be run on a SQL query tool for SAP HANA, express edition. For more information 
-- https://developers.sap.com/tutorials/mlb-hxe-tools-sql.html 

Author Benetti Mauro A.
Version: 1.0 15.03.2020
#########################################################################################################

##########################################
#- User 02 - Graph processing with HANA #
##########################################

-- INITIAL SYSTEM SET UP - data import
/*********************************************************/
-- The exercises use some data which is provided by SAP tutorials and SAP HANA Academy. (https://github.com/saphanaacademy/Graph)
-- This data was imported to your schema via flat file upload. In total contains Airports and flights . 
-- The workspace is used to use the abstraction of a graph to find the best route, neighbors and . 
-- The current maximum size for an LOB on SAP HANA is 2GB.

CREATE COLUMN TABLE "Airports" (
 "airportCode" NVARCHAR(3) NOT NULL,
 "airportName" NVARCHAR(100),
 "city" NVARCHAR(100),
 "country" NVARCHAR(100),
 "location" ST_GEOMETRY (4326),
 "altitude" INTEGER,
 "offsetUTC" INTEGER,
 "passengers" INTEGER,
 PRIMARY KEY ("airportCode"))
;

CREATE COLUMN TABLE "Routes" ("routeId" INTEGER NOT NULL generated by default as IDENTITY,
 "airlineCode" NVARCHAR(2) NOT NULL,
 "airlineName" NVARCHAR(100),
 "allianceName" NVARCHAR(100),
 "airportCodeOrigin" NVARCHAR(3) NOT NULL,
 "airportCodeDestination" NVARCHAR(3) NOT NULL,
 "distance" INTEGER,
 "duration" INTEGER,
 PRIMARY KEY ("routeId"))
;

insert into "Airports" values ('AMS','Amsterdam Airport Schiphol','Amsterdam','Netherlands',new ST_POINT('POINT(4.76388979 52.30860138)',4326),-11,1,64);
insert into "Airports" values ('ATL','Hartsfield Jackson Atlanta International Airport','Atlanta','United States',new ST_POINT('POINT(-84.42810059 33.63669968)',4326),1026,-5,104);
insert into "Airports" values ('CDG','Charles de Gaulle International Airport','Paris','France',new ST_POINT('POINT(2.549999952 49.01279831)',4326),392,1,66);
insert into "Airports" values ('DFW','Dallas Fort Worth International Airport','Dallas-Fort Worth','United States',new ST_POINT('POINT(-97.03800201 32.89680099)',4326),607,-6,66);
insert into "Airports" values ('DXB','Dubai International Airport','Dubai','United Arab Emirates',new ST_POINT('POINT(55.36439896 25.25279999)',4326),62,4,84);
insert into "Airports" values ('FRA','Frankfurt am Main International Airport','Frankfurt','Germany',new ST_POINT('POINT(8.5705556 50.0333333)',4326),364,1,61);
insert into "Airports" values ('HND','Tokyo Haneda International Airport','Tokyo','Japan',new ST_POINT('POINT(139.779999 35.552299)',4326),35,9,80);
insert into "Airports" values ('JFK','John F Kennedy International Airport','New York','United States',new ST_POINT('POINT(-73.77890015 40.63980103)',4326),13,-5,58);
insert into "Airports" values ('LAX','Los Angeles International Airport','Los Angeles','United States',new ST_POINT('POINT(-118.4079971 33.94250107)',4326),125,-8,81);
insert into "Airports" values ('LHR','London Heathrow Airport','London','United Kingdom',new ST_POINT('POINT(-0.461941 51.4706)',4326),83,0,75);
insert into "Airports" values ('NTE','Nantes Atlantique Airport','Nantes','France',new ST_POINT('POINT(-1.610730052 47.15319824)',4326),90,1,5);
insert into "Airports" values ('ORD','Chicago O Hare International Airport','Chicago','United States',new ST_POINT('POINT(-87.90480042 41.97859955)',4326),672,-6,78);
insert into "Airports" values ('PDX','Portland International Airport','Portland','United States',new ST_POINT('POINT(-122.5979996 45.58869934)',4326),31,-8,17);
insert into "Airports" values ('PVG','Shanghai Pudong International Airport','Shanghai','China',new ST_POINT('POINT(121.8050003 31.14340019)',4326),13,8,66);
insert into "Airports" values ('SFO','San Francisco International Airport','San Francisco','United States',new ST_POINT('POINT(-122.375 37.6189994812011)',4326),13,-8,45);
insert into "Airports" values ('YVR','Vancouver International Airport','Vancouver','Canada',new ST_POINT('POINT(-123.183998108 49.193901062)',4326),14,-8,22);

insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('AF','Air France','SkyTeam','ATL','CDG',4394,9);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('AF','Air France','SkyTeam','CDG','ATL',4394,9);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('AF','Air France','SkyTeam','CDG','DXB',3259,7);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('AF','Air France','SkyTeam','CDG','FRA',280,1);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('AF','Air France','SkyTeam','CDG','HND',6046,14);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('AF','Air France','SkyTeam','CDG','JFK',3635,9);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('AF','Air France','SkyTeam','CDG','LAX',5669,12);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('AF','Air France','SkyTeam','CDG','LHR',216,1);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('AF','Air France','SkyTeam','CDG','NTE',231,2);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('AF','Air France','SkyTeam','CDG','ORD',4152,10);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('AF','Air France','SkyTeam','CDG','PVG',5771,13);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('AF','Air France','SkyTeam','CDG','SFO',5583,13);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('AF','Air France','SkyTeam','DXB','CDG',3259,8);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('AF','Air France','SkyTeam','FRA','CDG',280,2);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('AF','Air France','SkyTeam','HND','CDG',6046,14);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('AF','Air France','SkyTeam','JFK','CDG',3635,8);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('AF','Air France','SkyTeam','LAX','CDG',5669,13);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('AF','Air France','SkyTeam','LHR','CDG',216,2);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('AF','Air France','SkyTeam','NTE','CDG',231,2);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('AF','Air France','SkyTeam','ORD','CDG',4152,10);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('AF','Air France','SkyTeam','PVG','CDG',5771,12);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('AF','Air France','SkyTeam','SFO','CDG',5583,13);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('DL','Delta Air Lines','SkyTeam','AMS','ATL',4401,9);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('DL','Delta Air Lines','SkyTeam','AMS','JFK',3643,9);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('DL','Delta Air Lines','SkyTeam','AMS','PDX',5004,12);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('DL','Delta Air Lines','SkyTeam','ATL','AMS',4401,9);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('DL','Delta Air Lines','SkyTeam','ATL','CDG',4394,10);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('DL','Delta Air Lines','SkyTeam','ATL','DFW',731,2);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('DL','Delta Air Lines','SkyTeam','ATL','DXB',7599,16);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('DL','Delta Air Lines','SkyTeam','ATL','FRA',4615,10);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('DL','Delta Air Lines','SkyTeam','ATL','JFK',760,2);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('DL','Delta Air Lines','SkyTeam','ATL','LAX',1946,5);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('DL','Delta Air Lines','SkyTeam','ATL','LHR',4211,9);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('DL','Delta Air Lines','SkyTeam','ATL','ORD',606,2);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('DL','Delta Air Lines','SkyTeam','ATL','PDX',2172,5);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('DL','Delta Air Lines','SkyTeam','ATL','SFO',2139,5);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('DL','Delta Air Lines','SkyTeam','CDG','ATL',4394,9);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('DL','Delta Air Lines','SkyTeam','CDG','JFK',3635,8);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('DL','Delta Air Lines','SkyTeam','CDG','LAX',5669,13);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('DL','Delta Air Lines','SkyTeam','DFW','ATL',731,2);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('DL','Delta Air Lines','SkyTeam','DXB','ATL',7599,16);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('DL','Delta Air Lines','SkyTeam','FRA','ATL',4615,10);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('DL','Delta Air Lines','SkyTeam','FRA','JFK',3856,9);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('DL','Delta Air Lines','SkyTeam','HND','LAX',5488,13);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('DL','Delta Air Lines','SkyTeam','JFK','AMS',3643,8);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('DL','Delta Air Lines','SkyTeam','JFK','ATL',760,3);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('DL','Delta Air Lines','SkyTeam','JFK','CDG',3635,9);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('DL','Delta Air Lines','SkyTeam','JFK','DFW',1391,3);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('DL','Delta Air Lines','SkyTeam','JFK','FRA',3856,9);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('DL','Delta Air Lines','SkyTeam','JFK','LAX',2475,5);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('DL','Delta Air Lines','SkyTeam','JFK','LHR',3451,8);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('DL','Delta Air Lines','SkyTeam','JFK','ORD',740,2);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('DL','Delta Air Lines','SkyTeam','JFK','PDX',2454,5);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('DL','Delta Air Lines','SkyTeam','JFK','PVG',7392,15);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('DL','Delta Air Lines','SkyTeam','JFK','SFO',2586,7);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('DL','Delta Air Lines','SkyTeam','LAX','ATL',1946,4);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('DL','Delta Air Lines','SkyTeam','LAX','HND',5488,13);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('DL','Delta Air Lines','SkyTeam','LAX','JFK',2475,5);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('DL','Delta Air Lines','SkyTeam','LHR','ATL',4211,9);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('DL','Delta Air Lines','SkyTeam','LHR','JFK',3451,8);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('DL','Delta Air Lines','SkyTeam','ORD','ATL',606,3);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('DL','Delta Air Lines','SkyTeam','ORD','CDG',4152,9);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('DL','Delta Air Lines','SkyTeam','PDX','AMS',5004,11);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('DL','Delta Air Lines','SkyTeam','PDX','ATL',2172,5);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('DL','Delta Air Lines','SkyTeam','PDX','JFK',2454,5);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('DL','Delta Air Lines','SkyTeam','PVG','JFK',7392,16);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('DL','Delta Air Lines','SkyTeam','PVG','SFO',6150,14);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('DL','Delta Air Lines','SkyTeam','SFO','ATL',2139,5);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('DL','Delta Air Lines','SkyTeam','SFO','JFK',2586,6);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('DL','Delta Air Lines','SkyTeam','SFO','PVG',6150,13);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('KL','KLM Royal Dutch Airlines','SkyTeam','AMS','ATL',4401,9);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('KL','KLM Royal Dutch Airlines','SkyTeam','AMS','DFW',4920,11);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('KL','KLM Royal Dutch Airlines','SkyTeam','AMS','DXB',3215,8);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('KL','KLM Royal Dutch Airlines','SkyTeam','AMS','JFK',3643,8);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('KL','KLM Royal Dutch Airlines','SkyTeam','AMS','LAX',5578,12);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('KL','KLM Royal Dutch Airlines','SkyTeam','AMS','LHR',231,2);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('KL','KLM Royal Dutch Airlines','SkyTeam','AMS','ORD',4120,10);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('KL','KLM Royal Dutch Airlines','SkyTeam','AMS','PVG',5549,13);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('KL','KLM Royal Dutch Airlines','SkyTeam','AMS','SFO',5473,13);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('KL','KLM Royal Dutch Airlines','SkyTeam','AMS','YVR',4804,11);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('KL','KLM Royal Dutch Airlines','SkyTeam','ATL','AMS',4401,10);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('KL','KLM Royal Dutch Airlines','SkyTeam','DFW','AMS',4920,11);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('KL','KLM Royal Dutch Airlines','SkyTeam','DXB','AMS',3215,8);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('KL','KLM Royal Dutch Airlines','SkyTeam','JFK','AMS',3643,8);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('KL','KLM Royal Dutch Airlines','SkyTeam','LAX','AMS',5578,12);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('KL','KLM Royal Dutch Airlines','SkyTeam','LHR','AMS',231,2);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('KL','KLM Royal Dutch Airlines','SkyTeam','ORD','AMS',4120,9);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('KL','KLM Royal Dutch Airlines','SkyTeam','PVG','AMS',5549,13);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('KL','KLM Royal Dutch Airlines','SkyTeam','SFO','AMS',5473,12);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('KL','KLM Royal Dutch Airlines','SkyTeam','YVR','AMS',4804,10);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('LH','Lufthansa','Star Alliance','AMS','FRA',228,1);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('LH','Lufthansa','Star Alliance','ATL','FRA',4615,10);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('LH','Lufthansa','Star Alliance','CDG','FRA',280,1);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('LH','Lufthansa','Star Alliance','DFW','FRA',5143,11);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('LH','Lufthansa','Star Alliance','DXB','FRA',3012,7);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('LH','Lufthansa','Star Alliance','FRA','AMS',228,2);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('LH','Lufthansa','Star Alliance','FRA','ATL',4615,11);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('LH','Lufthansa','Star Alliance','FRA','CDG',280,1);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('LH','Lufthansa','Star Alliance','FRA','DFW',5143,12);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('LH','Lufthansa','Star Alliance','FRA','DXB',3012,8);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('LH','Lufthansa','Star Alliance','FRA','HND',5831,12);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('LH','Lufthansa','Star Alliance','FRA','JFK',3856,8);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('LH','Lufthansa','Star Alliance','FRA','LAX',5806,12);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('LH','Lufthansa','Star Alliance','FRA','LHR',408,1);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('LH','Lufthansa','Star Alliance','FRA','ORD',4344,9);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('LH','Lufthansa','Star Alliance','FRA','PVG',5516,13);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('LH','Lufthansa','Star Alliance','FRA','SFO',5699,12);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('LH','Lufthansa','Star Alliance','FRA','YVR',5025,12);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('LH','Lufthansa','Star Alliance','HND','FRA',5831,13);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('LH','Lufthansa','Star Alliance','JFK','FRA',3856,8);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('LH','Lufthansa','Star Alliance','LAX','FRA',5806,12);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('LH','Lufthansa','Star Alliance','LHR','FRA',408,1);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('LH','Lufthansa','Star Alliance','ORD','FRA',4344,9);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('LH','Lufthansa','Star Alliance','PVG','FRA',5516,13);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('LH','Lufthansa','Star Alliance','SFO','FRA',5699,12);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('LH','Lufthansa','Star Alliance','YVR','FRA',5025,11);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('UA','United Airlines','Star Alliance','AMS','ORD',4120,10);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('UA','United Airlines','Star Alliance','ATL','SFO',2139,6);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('UA','United Airlines','Star Alliance','CDG','ORD',4152,9);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('UA','United Airlines','Star Alliance','CDG','SFO',5583,13);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('UA','United Airlines','Star Alliance','DFW','ORD',802,3);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('UA','United Airlines','Star Alliance','DFW','SFO',1464,3);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('UA','United Airlines','Star Alliance','FRA','ORD',4344,9);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('UA','United Airlines','Star Alliance','FRA','SFO',5699,12);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('UA','United Airlines','Star Alliance','JFK','LAX',2475,5);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('UA','United Airlines','Star Alliance','JFK','SFO',2586,7);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('UA','United Airlines','Star Alliance','LAX','JFK',2475,5);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('UA','United Airlines','Star Alliance','LAX','LHR',5456,12);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('UA','United Airlines','Star Alliance','LAX','ORD',1745,4);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('UA','United Airlines','Star Alliance','LAX','PVG',6485,15);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('UA','United Airlines','Star Alliance','LAX','SFO',337,1);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('UA','United Airlines','Star Alliance','LHR','LAX',5456,11);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('UA','United Airlines','Star Alliance','LHR','ORD',3953,9);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('UA','United Airlines','Star Alliance','LHR','SFO',5368,12);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('UA','United Airlines','Star Alliance','ORD','AMS',4120,10);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('UA','United Airlines','Star Alliance','ORD','CDG',4152,9);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('UA','United Airlines','Star Alliance','ORD','DFW',802,2);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('UA','United Airlines','Star Alliance','ORD','FRA',4344,9);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('UA','United Airlines','Star Alliance','ORD','LAX',1745,5);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('UA','United Airlines','Star Alliance','ORD','LHR',3953,8);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('UA','United Airlines','Star Alliance','ORD','PDX',1739,5);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('UA','United Airlines','Star Alliance','ORD','PVG',7057,15);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('UA','United Airlines','Star Alliance','ORD','SFO',1846,4);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('UA','United Airlines','Star Alliance','ORD','YVR',1764,4);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('UA','United Airlines','Star Alliance','PDX','ORD',1739,5);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('UA','United Airlines','Star Alliance','PDX','SFO',550,3);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('UA','United Airlines','Star Alliance','PVG','LAX',6485,15);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('UA','United Airlines','Star Alliance','PVG','ORD',7057,16);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('UA','United Airlines','Star Alliance','PVG','SFO',6150,13);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('UA','United Airlines','Star Alliance','SFO','ATL',2139,6);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('UA','United Airlines','Star Alliance','SFO','CDG',5583,13);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('UA','United Airlines','Star Alliance','SFO','DFW',1464,4);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('UA','United Airlines','Star Alliance','SFO','FRA',5699,12);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('UA','United Airlines','Star Alliance','SFO','JFK',2586,7);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('UA','United Airlines','Star Alliance','SFO','LAX',337,2);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('UA','United Airlines','Star Alliance','SFO','LHR',5368,11);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('UA','United Airlines','Star Alliance','SFO','ORD',1846,4);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('UA','United Airlines','Star Alliance','SFO','PDX',550,3);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('UA','United Airlines','Star Alliance','SFO','PVG',6150,13);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('UA','United Airlines','Star Alliance','SFO','YVR',800,2);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('UA','United Airlines','Star Alliance','YVR','ORD',1764,4);
insert into "Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") values ('UA','United Airlines','Star Alliance','YVR','SFO',800,3);

create graph workspace "Flights"
 edge table "Routes"
  source column "airportCodeOrigin"
  target column "airportCodeDestination"
  key column "routeId"
 vertex table "Airports"
  key column "airportCode"
;

/* openCypher
MATCH 	(a)-[e]->(b)
WHERE 	a.country = 'United States' AND 
		e.distance > 5000 AND 
		b.altitude < 20
RETURN 	a.airportCode AS airportCodeFrom, 
		b.airportCode AS airportCodeTo
*/

DROP TABLE "EDGES";
DROP TABLE "NODES";
DROP TABLE "Routes";
DROP TABLE "Airports";
DROP graph workspace "Flights"

--Generate data for Graph nodes from the food example
***************************************

--The $TA table you created in the previous step could already give some text analysis insights, but due to the flat 
--structure, it’s use case is fairly limited. The “Graph” model is much more versatile, since it requires two tables 
--(or views); one for the data of the nodes and vertices, and one for the edges. In the following steps, you will 
--create these two views, create a Graph workspace, and display its data. To create the nodes table, execute the 
--following statement:

CREATE VIEW "NODES_DATA" AS
 (
       SELECT * FROM
       (
             (     -- Nodes representing each TA_ENTITY in a document
                   SELECT
                         'TE-OR-'||TO_NVARCHAR("NAME")||'-'||TO_NVARCHAR("TA_OFFSET")||'-'||LENGTH("TA_TOKEN") ID,
                         TO_NVARCHAR("TA_TOKEN") NODE_NAME,
                         'TA_ENTITY' NODE_TYPE,
                         'TA_TOKEN' ATTR_NAME,
                         'NVARCHAR(5000)' ATTR_DATA_TYPE,
                         TO_NVARCHAR("TA_TOKEN") ATTR_VALUE
                   FROM "$TA_FOOD_SENTIMENT_INDEX"
                   WHERE "TA_TOKEN" IS NOT NULL
                   GROUP BY "NAME","TA_OFFSET","TA_TOKEN"
             )
             UNION
             (     -- Nodes representing each TA_OFFSET attribute of each TA_ENTITY
                   SELECT
                         'TE-M1-'||TO_NVARCHAR("NAME")||'-'||TO_NVARCHAR("TA_OFFSET")||'-'||LENGTH("TA_TOKEN") ID,
                         TO_NVARCHAR("TA_TOKEN") NODE_NAME,
                         'TA_ENTITY_M1' NODE_TYPE,
                         'TA_OFFSET' ATTR_NAME,
                         'BIGINT' ATTR_DATA_TYPE,
                         TO_NVARCHAR("TA_OFFSET") ATTR_VALUE
                   FROM "$TA_FOOD_SENTIMENT_INDEX"
                   WHERE "TA_TOKEN" IS NOT NULL
                   GROUP BY "NAME","TA_OFFSET","TA_TOKEN"
             )
             UNION
             (     -- Nodes representing each extracted TA_TYPE
                   SELECT
                         'TT-OR-'||TO_NVARCHAR("TA_TYPE") ID,
                         TO_NVARCHAR("TA_TYPE") NODE_NAME,
                         'TA_TYPE' NODE_TYPE,
                         'TA_TYPE' ATTR_NAME,
                         'NVARCHAR(100)' ATTR_DATA_TYPE,
                         TO_NVARCHAR("TA_TYPE") ATTR_VALUE
                   FROM "$TA_FOOD_SENTIMENT_INDEX"
                   WHERE "TA_TYPE" IS NOT NULL
                               AND "TA_TYPE" NOT LIKE 'MWT_%'
                               AND "TA_TYPE_EXPANDED" IS NULL
                   GROUP BY "TA_TYPE"
             )
             UNION
             (     -- Nodes representing each extracted POS types
                   SELECT
                         'TP-OR-'||(CASE WHEN "TA_TYPE" LIKE 'MWT_%' THEN TO_NVARCHAR("TA_TYPE") ELSE TO_NVARCHAR("TA_TYPE_EXPANDED") END) ID,
                         CASE WHEN "TA_TYPE" LIKE 'MWT_%' THEN TO_NVARCHAR("TA_TYPE") ELSE TO_NVARCHAR("TA_TYPE_EXPANDED") END NODE_NAME,
                         'TA_POS' NODE_TYPE,
                         'TA_TYPE_EXPANDED' ATTR_NAME,
                         'NVARCHAR(100)' ATTR_DATA_TYPE,
                         TO_NVARCHAR("TA_TYPE_EXPANDED") ATTR_VALUE
                   FROM "$TA_FOOD_SENTIMENT_INDEX"
                   WHERE "TA_TYPE_EXPANDED" IS NOT NULL OR "TA_TYPE" LIKE 'MWT_%'
                   GROUP BY "TA_TYPE","TA_TYPE_EXPANDED"
             )
             UNION
             (     -- Nodes representing each extracted TA_NORMALIZED form
                   SELECT
                         'TN-OR-'||TO_NVARCHAR("TA_NORMALIZED") ID,
                         TO_NVARCHAR("TA_NORMALIZED") NODE_NAME,
                         'TA_NORMALIZED' NODE_TYPE,
                         'TA_NORMALIZED' ATTR_NAME,
                         'NVARCHAR(5000)' ATTR_DATA_TYPE,
                         TO_NVARCHAR("TA_NORMALIZED") ATTR_VALUE
                   FROM "$TA_FOOD_SENTIMENT_INDEX"
                   WHERE "TA_TYPE" NOT IN ('DATE','STOPWORD')
                               AND "TA_RULE" <> 'LXP'
                               AND "TA_TYPE" NOT LIKE 'MWT_%'
                               AND "TA_NORMALIZED" IS NOT NULL
                   GROUP BY "TA_NORMALIZED"
             )
             UNION
             (     -- Nodes representing each extracted TA_STEM
                   SELECT
                         'TS-OR-'||TO_NVARCHAR(COALESCE("TA_STEM","TA_NORMALIZED")) ID,
                         TO_NVARCHAR(COALESCE("TA_STEM","TA_NORMALIZED")) NODE_NAME,
                         'TA_STEM' NODE_TYPE,
                         'TA_STEM' ATTR_NAME,
                         'NVARCHAR(5000)' ATTR_DATA_TYPE,
                         TO_NVARCHAR(COALESCE("TA_STEM","TA_NORMALIZED")) ATTR_VALUE
                   FROM "$TA_FOOD_SENTIMENT_INDEX"
                   WHERE "TA_RULE" = 'LXP' AND COALESCE("TA_STEM","TA_NORMALIZED") IS NOT NULL
                   GROUP BY COALESCE("TA_STEM","TA_NORMALIZED")
             )
             UNION
             (     -- Nodes representing each normalized (and post-processed) DATE
                   SELECT
                         'DT-OR-'||REPLACE(TO_NVARCHAR("TA_NORMALIZED"),' ','_') ID,
                         TO_NVARCHAR("TA_NORMALIZED") NODE_NAME,
                         'DATE' NODE_TYPE,
                         'TA_NORMALIZED' ATTR_NAME,
                         'NVARCHAR(5000)' ATTR_DATA_TYPE,
                         TO_NVARCHAR("TA_NORMALIZED") ATTR_VALUE
                   FROM "$TA_FOOD_SENTIMENT_INDEX"
                   WHERE "TA_TYPE" = 'DATE'
                               AND "TA_NORMALIZED" IS NOT NULL
                   GROUP BY "TA_NORMALIZED"
             )
             UNION
             (     -- Nodes representing each processed DOCUMENT
                   SELECT
                         'DO-OR-'||TO_NVARCHAR("NAME") ID,
                         TO_NVARCHAR("NAME") NODE_NAME,
                         'DOCUMENT' NODE_TYPE,
                         'NAME' ATTR_NAME,
                         'INTEGER' ATTR_DATA_TYPE,
                         TO_NVARCHAR("NAME") ATTR_VALUE
                   FROM "$TA_FOOD_SENTIMENT_INDEX"
                   WHERE "NAME" IS NOT NULL
                   GROUP BY "NAME"
             )
             UNION
             (     -- Nodes representing each processed PARAGRAPH in a document
                   SELECT
                         'PG-OR-'||TO_NVARCHAR("NAME")||'-'||TO_NVARCHAR("TA_PARAGRAPH") ID,
                         TO_NVARCHAR("TA_PARAGRAPH") NODE_NAME,
                         'PARAGRAPH' NODE_TYPE,
                         'TA_PARAGRAPH' ATTR_NAME,
                         'INTEGER' ATTR_DATA_TYPE,
                         TO_NVARCHAR("TA_PARAGRAPH") ATTR_VALUE
                   FROM "$TA_FOOD_SENTIMENT_INDEX"
                   WHERE "TA_PARAGRAPH" IS NOT NULL
                   GROUP BY "NAME", "TA_PARAGRAPH"
             )
             UNION
             (     -- Nodes representing each processed SENTENCE in a document
                   SELECT
                         'ST-OR-'||TO_NVARCHAR("NAME")||'-'||TO_NVARCHAR("TA_SENTENCE") ID,
                         TO_NVARCHAR("TA_SENTENCE") NODE_NAME,
                         'SENTENCE' NODE_TYPE,
                         'TA_SENTENCE' ATTR_NAME,
                         'INTEGER' ATTR_DATA_TYPE,
                         TO_NVARCHAR("TA_SENTENCE") ATTR_VALUE
                   FROM "$TA_FOOD_SENTIMENT_INDEX"
                   WHERE "TA_SENTENCE" IS NOT NULL
                   GROUP BY "NAME", "TA_SENTENCE"
             )
             UNION
             (     -- Nodes representing each processed LANGUAGE
                   SELECT
                         'LG-OR-'||TO_NVARCHAR("TA_LANGUAGE") ID,
                         TO_NVARCHAR("TA_LANGUAGE") NODE_NAME,
                         'LANGUAGE' NODE_TYPE,
                         'TA_LANGUAGE' ATTR_NAME,
                         'INTEGER' ATTR_DATA_TYPE,
                         TO_NVARCHAR("TA_LANGUAGE") ATTR_VALUE
                   FROM "$TA_FOOD_SENTIMENT_INDEX"
                   WHERE "TA_LANGUAGE" IS NOT NULL
                   GROUP BY "TA_LANGUAGE"
             )
       )
 );
-- 
--Step 6: Generate data for Graph edges
***************************************
CREATE VIEW  "EDGES_DATA" AS
(
      SELECT * FROM
      (
            (
                  SELECT
                        'TE-OR-'||TO_NVARCHAR("NAME")||'-'||TO_NVARCHAR("TA_OFFSET")||'-'||LENGTH("TA_TOKEN")||'-'||'PG-OR-'||TO_NVARCHAR("NAME")||'-'||TO_NVARCHAR("TA_PARAGRAPH") ID,
                        'TE-OR-'||TO_NVARCHAR("NAME")||'-'||TO_NVARCHAR("TA_OFFSET")||'-'||LENGTH("TA_TOKEN") src_id,
                        'PG-OR-'||TO_NVARCHAR("NAME")||'-'||TO_NVARCHAR("TA_PARAGRAPH") dest_id,
                        'TE-PG' EDGE_TYPE,
                        0 "DISTANCE"
                  FROM  "$TA_FOOD_SENTIMENT_INDEX"
                  GROUP BY "NAME","TA_OFFSET","TA_TOKEN","TA_PARAGRAPH"
            )
            UNION
            (
                  SELECT
                        'TE-OR-'||TO_NVARCHAR("NAME")||'-'||TO_NVARCHAR("TA_OFFSET")||'-'||LENGTH("TA_TOKEN")||'-'||'ST-OR-'||TO_NVARCHAR("NAME")||'-'||TO_NVARCHAR("TA_SENTENCE") ID,
                        'TE-OR-'||TO_NVARCHAR("NAME")||'-'||TO_NVARCHAR("TA_OFFSET")||'-'||LENGTH("TA_TOKEN") src_id,
                        'ST-OR-'||TO_NVARCHAR("NAME")||'-'||TO_NVARCHAR("TA_SENTENCE") dest_id,
                        'TE-ST' EDGE_TYPE,
                        0 "DISTANCE"
                  FROM  "$TA_FOOD_SENTIMENT_INDEX"
                  GROUP BY "NAME","TA_OFFSET","TA_TOKEN","TA_SENTENCE"
            )
            UNION
            (
                  SELECT
                        'TE-OR-'||TO_NVARCHAR("NAME")||'-'||TO_NVARCHAR("TA_OFFSET")||'-'||LENGTH("TA_TOKEN")||'-'||'TS-OR-'||TO_NVARCHAR(COALESCE("TA_STEM","TA_NORMALIZED")) ID,
                        'TE-OR-'||TO_NVARCHAR("NAME")||'-'||TO_NVARCHAR("TA_OFFSET")||'-'||LENGTH("TA_TOKEN") src_id,
                        'TS-OR-'||TO_NVARCHAR(COALESCE("TA_STEM","TA_NORMALIZED")) dest_id,
                        'TE-TS' EDGE_TYPE,
                        0 "DISTANCE"
                  FROM  "$TA_FOOD_SENTIMENT_INDEX"
                  WHERE "TA_RULE" = 'LXP' AND COALESCE("TA_STEM","TA_NORMALIZED") IS NOT NULL
                  GROUP BY "NAME","TA_OFFSET","TA_TOKEN",COALESCE("TA_STEM","TA_NORMALIZED")
            )
            UNION
            (
                  SELECT
                        'TE-OR-'||TO_NVARCHAR("NAME")||'-'||TO_NVARCHAR("TA_OFFSET")||'-'||LENGTH("TA_TOKEN")||'-'||'TP-OR-'||(CASE WHEN "TA_TYPE" LIKE 'MWT_%' THEN TO_NVARCHAR("TA_TYPE") ELSE TO_NVARCHAR("TA_TYPE_EXPANDED") END) ID,
                        'TE-OR-'||TO_NVARCHAR("NAME")||'-'||TO_NVARCHAR("TA_OFFSET")||'-'||LENGTH("TA_TOKEN") src_id,
                        'TP-OR-'||(CASE WHEN "TA_TYPE" LIKE 'MWT_%' THEN TO_NVARCHAR("TA_TYPE") ELSE TO_NVARCHAR("TA_TYPE_EXPANDED") END) dest_id,
                        'TE-TP' EDGE_TYPE,
                        0 "DISTANCE"
                  FROM  "$TA_FOOD_SENTIMENT_INDEX"
                  WHERE "TA_TYPE_EXPANDED" IS NOT NULL OR "TA_TYPE" LIKE 'MWT_%'
                  GROUP BY "NAME","TA_OFFSET","TA_TOKEN","TA_TYPE","TA_TYPE_EXPANDED"
            )
            UNION
            (
                  SELECT
                        'TE-OR-'||TO_NVARCHAR("NAME")||'-'||TO_NVARCHAR("TA_OFFSET")||'-'||LENGTH("TA_TOKEN")||'-'||'DT-OR-'||REPLACE(TO_NVARCHAR("TA_NORMALIZED"),' ','_') ID,
                        'TE-OR-'||TO_NVARCHAR("NAME")||'-'||TO_NVARCHAR("TA_OFFSET")||'-'||LENGTH("TA_TOKEN") src_id,
                        'DT-OR-'||REPLACE(TO_NVARCHAR("TA_NORMALIZED"),' ','_') dest_id,
                        'TE-DT' EDGE_TYPE,
                        0 "DISTANCE"
                  FROM  "$TA_FOOD_SENTIMENT_INDEX"
                  WHERE "TA_TYPE" = 'DATE'
                              AND "TA_NORMALIZED" IS NOT NULL
                  GROUP BY "NAME","TA_OFFSET","TA_TOKEN","TA_NORMALIZED"
            )
            UNION
            (
                  SELECT
                        'TE-OR-'||TO_NVARCHAR("NAME")||'-'||TO_NVARCHAR("TA_OFFSET")||'-'||LENGTH("TA_TOKEN")||'-'||'TN-OR-'||TO_NVARCHAR("TA_NORMALIZED") ID,
                        'TE-OR-'||TO_NVARCHAR("NAME")||'-'||TO_NVARCHAR("TA_OFFSET")||'-'||LENGTH("TA_TOKEN") src_id,
                        'TN-OR-'||TO_NVARCHAR("TA_NORMALIZED") dest_id,
                        'TE-TN' EDGE_TYPE,
                        0 "DISTANCE"
                  FROM  "$TA_FOOD_SENTIMENT_INDEX"
                  WHERE "TA_TYPE" NOT IN ('DATE','STOPWORD')
                              AND "TA_RULE" <> 'LXP'
                              AND "TA_TYPE" NOT LIKE 'MWT_%'
                              AND "TA_NORMALIZED" IS NOT NULL
                  GROUP BY "NAME","TA_OFFSET","TA_TOKEN","TA_NORMALIZED"
            )
            UNION
            (
                  SELECT
                        'ST-OR-'||TO_NVARCHAR("NAME")||'-'||TO_NVARCHAR("TA_SENTENCE")||'-'||'PG-OR-'||TO_NVARCHAR("NAME")||'-'||TO_NVARCHAR("TA_PARAGRAPH") ID,
                        'ST-OR-'||TO_NVARCHAR("NAME")||'-'||TO_NVARCHAR("TA_SENTENCE") src_id,
                        'PG-OR-'||TO_NVARCHAR("NAME")||'-'||TO_NVARCHAR("TA_PARAGRAPH") dest_id,
                        'ST-PG' EDGE_TYPE,
                        1 "DISTANCE"
                  FROM  "$TA_FOOD_SENTIMENT_INDEX"
                  GROUP BY "NAME", "TA_SENTENCE", "TA_PARAGRAPH"
            )
            UNION
            (
                  SELECT
                        'PG-OR-'||TO_NVARCHAR("NAME")||'-'||TO_NVARCHAR("TA_PARAGRAPH")||'-'||'DO-OR-'||TO_NVARCHAR("NAME") ID,
                        'PG-OR-'||TO_NVARCHAR("NAME")||'-'||TO_NVARCHAR("TA_PARAGRAPH") src_id,
                        'DO-OR-'||TO_NVARCHAR("NAME") dest_id,
                        'PG-DO' EDGE_TYPE,
                        1 "DISTANCE"
                  FROM  "$TA_FOOD_SENTIMENT_INDEX"
                  GROUP BY "NAME", "TA_PARAGRAPH"
            )
            UNION
            (
                  SELECT
                        'ST-OR-'||TO_NVARCHAR("NAME")||'-'||TO_NVARCHAR("TA_SENTENCE")||'-'||'DO-OR-'||TO_NVARCHAR("NAME") ID,
                        'ST-OR-'||TO_NVARCHAR("NAME")||'-'||TO_NVARCHAR("TA_SENTENCE") src_id,
                        'DO-OR-'||TO_NVARCHAR("NAME") dest_id,
                        'ST-DO' EDGE_TYPE,
                        0 "DISTANCE"
                  FROM  "$TA_FOOD_SENTIMENT_INDEX"
                  GROUP BY "NAME", "TA_SENTENCE"
            )
            UNION
            (
                  SELECT
                        'DO-OR-'||TO_NVARCHAR("NAME")||'-'||'LG-OR-'||TO_NVARCHAR("TA_LANGUAGE") ID,
                        'DO-OR-'||TO_NVARCHAR("NAME") src_id,
                        'LG-OR-'||TO_NVARCHAR("TA_LANGUAGE") dest_id,
                        'DO-LG' EDGE_TYPE,
                        0 "DISTANCE"
                  FROM  "$TA_FOOD_SENTIMENT_INDEX"
                  GROUP BY "NAME", "TA_LANGUAGE"
            )
            UNION
            (
                  SELECT
                        'TE-OR-'||TO_NVARCHAR("NAME")||'-'||TO_NVARCHAR("TA_OFFSET")||'-'||LENGTH("TA_TOKEN")||'-'||'TT-OR-'||TO_NVARCHAR("TA_TYPE") ID,
                        'TE-OR-'||TO_NVARCHAR("NAME")||'-'||TO_NVARCHAR("TA_OFFSET")||'-'||LENGTH("TA_TOKEN") src_id,
                        'TT-OR-'||TO_NVARCHAR("TA_TYPE") dest_id,
                        'TE-TT' EDGE_TYPE,
                        0 "DISTANCE"
                  FROM  "$TA_FOOD_SENTIMENT_INDEX"
                  WHERE "TA_TYPE" IS NOT NULL
                        AND "TA_TYPE" NOT LIKE 'MWT_%'
                        AND "TA_TYPE_EXPANDED" IS NULL
                  GROUP BY "NAME","TA_OFFSET","TA_TOKEN","TA_TYPE"
            )
            UNION
            (
                  SELECT
                        'TE-OR-'||TO_NVARCHAR(B."NAME")||'-'||TO_NVARCHAR(B."TA_OFFSET")||'-'||LENGTH(B."TA_TOKEN")||'-constitutes-'||'TE-OR-'||TO_NVARCHAR(A."NAME")||'-'||TO_NVARCHAR(A."TA_OFFSET")||'-'||LENGTH(A."TA_TOKEN") ID,
                        'TE-OR-'||TO_NVARCHAR(B."NAME")||'-'||TO_NVARCHAR(B."TA_OFFSET")||'-'||LENGTH(B."TA_TOKEN") src_id,
                        'TE-OR-'||TO_NVARCHAR(A."NAME")||'-'||TO_NVARCHAR(A."TA_OFFSET")||'-'||LENGTH(A."TA_TOKEN") dest_id,
                        'constitutes' EDGE_TYPE,
                        0 "DISTANCE"
                  FROM
                         "$TA_FOOD_SENTIMENT_INDEX" A
                        LEFT JOIN
                         "$TA_FOOD_SENTIMENT_INDEX" B
                        ON    A."NAME" = B."NAME"
                              AND (A."NAME",A."TA_OFFSET",LENGTH(A."TA_TOKEN")) <> (B."NAME",B."TA_OFFSET",LENGTH(B."TA_TOKEN"))
                              AND A."TA_OFFSET" <= B."TA_OFFSET"
                              AND A."TA_OFFSET" + LENGTH(A."TA_TOKEN") >= B."TA_OFFSET" + LENGTH(B."TA_TOKEN")
                  WHERE B."NAME" IS NOT NULL
                  GROUP BY B."NAME",B."TA_OFFSET",B."TA_TOKEN",A."NAME",A."TA_OFFSET",A."TA_TOKEN"
            )
            UNION
            (
                  SELECT
                        'TE-OR-'||TO_NVARCHAR("CHILD"."NAME")||'-'||TO_NVARCHAR("CHILD"."TA_OFFSET")||'-'||LENGTH("CHILD"."TA_TOKEN") || '-is_SubEntity_of-' || 'TE-OR-'||TO_NVARCHAR("PARENT"."NAME")||'-'||TO_NVARCHAR("PARENT"."TA_OFFSET")||'-'||LENGTH("PARENT"."TA_TOKEN") ID,
                        'TE-OR-'||TO_NVARCHAR("CHILD"."NAME")||'-'||TO_NVARCHAR("CHILD"."TA_OFFSET")||'-'||LENGTH("CHILD"."TA_TOKEN") src_id,
                        'TE-OR-'||TO_NVARCHAR("PARENT"."NAME")||'-'||TO_NVARCHAR("PARENT"."TA_OFFSET")||'-'||LENGTH("PARENT"."TA_TOKEN") dest_id,
                        'is_SubEntity_of' edge_type,
                        1 "DISTANCE"
                  FROM
                         "$TA_FOOD_SENTIMENT_INDEX"
                        "CHILD"
                        INNER JOIN
                         "$TA_FOOD_SENTIMENT_INDEX"
                        "PARENT"
                        ON "PARENT"."NAME" = "CHILD"."NAME"
                        AND "PARENT"."TA_RULE" = "CHILD"."TA_RULE"
                        AND "PARENT"."TA_COUNTER" = "CHILD"."TA_PARENT"
                        AND "CHILD"."TA_RULE" <> 'Grammatical Role'
            )
            UNION
            (
                  SELECT
                        'TE-OR-'||TO_NVARCHAR("CHILD"."NAME")||'-'||TO_NVARCHAR("CHILD"."TA_OFFSET")||'-'||LENGTH("CHILD"."TA_TOKEN") || '-is_' || "CHILD"."TA_TYPE" || '_of-' || 'TE-OR-'||TO_NVARCHAR("PARENT"."NAME")||'-'||TO_NVARCHAR("PARENT"."TA_OFFSET")||'-'||LENGTH("PARENT"."TA_TOKEN") ID,
                        'TE-OR-'||TO_NVARCHAR("CHILD"."NAME")||'-'||TO_NVARCHAR("CHILD"."TA_OFFSET")||'-'||LENGTH("CHILD"."TA_TOKEN") src_id,
                        'TE-OR-'||TO_NVARCHAR("PARENT"."NAME")||'-'||TO_NVARCHAR("PARENT"."TA_OFFSET")||'-'||LENGTH("PARENT"."TA_TOKEN") dest_id,
                        'is_' || "CHILD"."TA_TYPE" || '_of' edge_type,
                        1 "DISTANCE"
                  FROM
                         "$TA_FOOD_SENTIMENT_INDEX"
                        "CHILD"
                        INNER JOIN
                         "$TA_FOOD_SENTIMENT_INDEX"
                        "PARENT"
                        ON "PARENT"."NAME" = "CHILD"."NAME"
                        AND "PARENT"."TA_RULE" = "CHILD"."TA_RULE"
                        AND "PARENT"."TA_COUNTER" = "CHILD"."TA_PARENT"
                        AND "CHILD"."TA_RULE" = 'Grammatical Role'
            )
      )
);

--Step 7: Create Graph Workspace

--Although you can directly use the two views in the Graph workspace, copying the view results into dedicated tables 
--performs much faster. Also, the Graph Viewer only supports direct table access. First, create the NODES table and 
--populate it with the NODES_DATA view result:

CREATE COLUMN TABLE "NODES" (
       "ID" NVARCHAR(5000) PRIMARY KEY, -- REQUIRED PRIMARY KEY FIELD FOR GRAPH ENGINE
       "NODE_NAME" NVARCHAR(5000),
       "NODE_TYPE" NVARCHAR(100),
       "ATTR_NAME" NVARCHAR(100),
       "ATTR_DATA_TYPE" NVARCHAR(100),
       "ATTR_VALUE" NVARCHAR(5000)
);     

SELECT * FROM NODES_DATA INTO NODES;

--Then, create the EDGES table and populate it with the EDGES_DATA view result:

CREATE COLUMN TABLE "EDGES" (
       "ID" NVARCHAR(5000) UNIQUE NOT NULL, -- REQUIRED UNIQUE FIELD FOR GRAPH ENGINE
       "SRC_ID" NVARCHAR(5000) NOT NULL REFERENCES "NODES" ("ID") ON UPDATE CASCADE ON DELETE CASCADE, -- REQUIRED FOREIGN KEY FIELD FOR GRAPH ENGINE
       "DEST_ID" NVARCHAR(5000) NOT NULL REFERENCES "NODES" ("ID") ON UPDATE CASCADE ON DELETE CASCADE, -- REQUIRED FOREIGN KEY FIELD FOR GRAPH ENGINE
       "EDGE_TYPE" NVARCHAR(100),
       "DISTANCE" INTEGER
);

SELECT * FROM EDGES_DATA INTO EDGES;

--Now, create a Graph workspace:

CREATE GRAPH WORKSPACE  "Food_Graph"
  EDGE TABLE  "EDGES_DATA"
  SOURCE COLUMN "SRC_ID"
  TARGET COLUMN "DEST_ID"
  KEY COLUMN "ID"
  VERTEX TABLE  "NODES_DATA"
  KEY COLUMN "ID";


--Step 8: Display the results using Graph Viewer

--The two Graph tables are now created, populated with the contents from the $TA table. The Graph workspace can now 
--be visualized using the Graph Visualizer in your SAP HANA Database Explorer.


DROP TABLE food_analysis
DROP TABLE food_sentiment
DROP TABLE food_analysis
DROP TABLE food_analysis
DROP graph workspace "Food_Graph"

